apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:2Z2zNN5kMGAm7rY1+xX97Y00BhIziviOABFPHlfH1BltG3DK501WjR5Wikt52W/qXazGicd1NJ/I9RxBYeOs0B0kRWVl6XzVBZw4jtc/qoK2Jjg/sfbcu0npxccyNPP7zv0O0krAw/HOPPiRkqd7KK31FuW2RGV6eTv31ES19+7g9uJBZOz+0ZJrL+kN5ZHY3wwFCijvIB7AurfQL4taKdmYjuBF2eLzHDqdnS+7cX6QlzV+r9XOlw==,iv:+xfJnlQUFgtw/zchfyRIlzJ+BFVUmyJSNyu9FB9TM/c=,tag:GqNOf7Tjzx/MBUWANkkxtg==,type:str]
sops:
  age:
    - recipient: age1qlg79k9uz2a523qvklflq5xzrx7w9h8hjj8hhjg5spqr2he57acqret8fl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEd1JwSjJwcHVaM0xPdXRR
        SFlrVFJjMjdMb3ZkZXkvSzRnWjRiQkRiVnlRCmdiK29tNkxxNm1PQWU2SFF6WWkv
        a2JDL2VoK1orMkpiVUpnV0gyLzJvZkkKLS0tIFkySlN4MXFwSjNaa3NKODdFMlBy
        RHkvSVpEUGlpOU5MQmVYYkFtcjgrSGsKwDoxJREl3ST/kiSj6Nk4z8hpfAS888kP
        qsdeaeqKK9kPHKBJbTvy4aE7NvlzulOOB/qk5MRxe4SxxVLNHt3XDA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-14T12:24:49Z"
  mac: ENC[AES256_GCM,data:iCFQ9qQR7k7TSuiZYApGuHmljMuzzt1Vi4JYYMWQS3rmQr5F8pCGkNxdpmAjfZUrWwzXT68x1AoC9dMN7yxfKJUovwWfB2PGVlkWy/ToxzQmR3Ydd+FqmLDrBA1QN7r1dCue8aMrdIHzXgcmzmBHsuc/ZJ2q4m5XFut9k2xOEwc=,iv:1HOswzzHDQcWn0Ika2GoeJRZQfeKeEcZjBEjOspil60=,tag:qBAe1KhGH7VluKDa8h4nCQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
