apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:58KWnMFdIrE=,iv:Kud7YL/paVos1g2khfAXYYFx6b4Fn1mRZf+7O2kiSIE=,tag:juf7z3bFPcVRgWfPmRWmhg==,type:str]
sops:
  age:
    - recipient: age1qlg79k9uz2a523qvklflq5xzrx7w9h8hjj8hhjg5spqr2he57acqret8fl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUDB6cGRaMWhpOEo2d2VP
        ai9qV1VVYi9RYU95empvdEVTM1R2TmxxV0hzCnJVengyRjZUUkJkV2FKOGJQcUo4
        dk5weFhFNVJTeHhjZ3ViMThBc1Q2WWcKLS0tIERmS0hSZG1GckNkMklKVVIvVUto
        V3RQWVZNRWdJLzhPam9GYmtpM0M1OUUK6Y0HlD9utD0ObtjdAHSCyvJfxugnDidh
        kP4fgL+dj0X2TrZ9LBrk8Hq31BbzME2NXBabzg/ubwaZ4iyysXR5ug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-14T12:24:49Z"
  mac: ENC[AES256_GCM,data:3k725BNUx1XB9GUIudyeymdwWgVbWMtoAKIKeZFE2DOW/GajSRVN0DfmRKkyN52UitSPxBXgROuVlEr5URZFmWQV1Tfeg8wpyFOKhW/8xa8n43mtUKyPwKSWMU0fzRiv9VTXzyHDgG+YqNPuQSA3wxyWqXSNEV6aP/Xgr2GzrFQ=,iv:oXhermhvLYASAdN8BY5JcgYGGmjPEvifvpOt8YqTTdw=,tag:4j3tsNaD3a2K6kBHCguriA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
