apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:AmtNAJLSDi1Izb2XD8Mvs2b98T7oJ2yV1bw6g1K4ej8=,iv:ozWzAK1uNXR+KkuThuiaOEmqsAsLlZCy+23FTdawgds=,tag:MGorF1fqfp4bujrjGMDd2g==,type:str]
sops:
  age:
    - recipient: age1qlg79k9uz2a523qvklflq5xzrx7w9h8hjj8hhjg5spqr2he57acqret8fl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnekFsaFgwTFAvSDh3TStt
        MmlnNVcrdXJKU2hlN0UzdFp4SWhxMEFJT2lVClUrZVBWUi8xWXFGU20vdmdmOGJU
        SUNvMThvWHR1MHJuUmw5U1pUK3VjZ00KLS0tIDJ0cnBGaFp2MGlYMkprVzBYdit3
        bCs3TjNQeXJSNjBod01PNFRTV3gxSWMKBhD6wDTb5g1kC0xTPcNW6zQmg/9hEpu+
        7U6P/3caBTAkg/kR/JeyTh8AsXc1m+NjgIE5A/IEeLfxXs84hXFoow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-14T12:24:49Z"
  mac: ENC[AES256_GCM,data:/RXOphcU+it4hHkiQHKtnucGfok/hQ1UlvgrL6c9jT0mZom49BiNr65sOALMfiX3KzB6Ce+ULwu0ek9DuqwmAgaHF0azSsMB0/HRrpgE9Bo2vC36i4WwT5HaOD3zF3PauXn1dyJwJy3p5umPlimi2Whjk6HjBKLUr2ncOhjJJCI=,iv:t07wBgr8VfzVVJL55O0WDi8mpgnzTmdZ2IWov2hIKCc=,tag:5Hp5u1TZMkta31gj14e2Kw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
