apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:LLG04uxgblOO6f1dXFm3GP734wjdvLafP0vBgpu0C2qHLN7IHvZ1eZR1tLzciJdWJu9wBuswqYHFtO0EPIze/FW6eTEFIuhJIT1+ewytTGJtPzr0tC3LBFqKrcLNx691U7c0QDY/UYWLcct/AqUcWRyOaSJ1P18rwBh1accDhE4yfT1cfL4xXpXxtBRi3HOxgHeBrwHjMgDA9X/59VUP85mD33Oc6Z2DrQj/jaiqvRyYqfqB,iv:rZm9PPP8CqggqkEEMwVDzwgI4bTmu+M5GNkAEctBQQ8=,tag:qtUG9NT4CyFVaCN8jKTI9Q==,type:str]
sops:
  age:
    - recipient: age1qlg79k9uz2a523qvklflq5xzrx7w9h8hjj8hhjg5spqr2he57acqret8fl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINDhHK1BSWk9YZkkyUXd2
        bTEydUZybU1ndnlXYWtUT0FNZHNSajdXdTE0CmI5NnFySElwTjFmQVFrdStGR3FU
        VHZGQko3TzZRZ1NhSk5Vb3FRdCtQSzAKLS0tIDZoQnZvNWxUSjZrSEVGZGE4RU5a
        UEd4K3hpajV2YTZ5ZTJUbDcvT0JOV2MKNLYVrLcfl3o7So00nENO/yMb/jOy+9cH
        NMINu8THQvWUw1MwmwUkRi+ha4RR04P3w7gO81lV899mSC74PlAeJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-14T12:24:49Z"
  mac: ENC[AES256_GCM,data:Qc08sPJMygE58ZUBetJKHMr2YeWXdKmUl5OikIR5P26AmwBMSLigdwTp+l1FpPlbDuaF977STRP2XwHJpCBD8xLxOOr0RZE92pmmm1/CgoEv/+Hs2tqQzHAI1z37hYCNESGMZoyV+U3lHIfXanFunzSCeibS0lJV3IgFpPP2tGo=,iv:Kf72db7Tc+D/eY6geWdZsT/HNPOlIszkv0MB4GGDxT8=,tag:s4eoMS1h/nIrhK87Yixvsw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
