apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:4s1jW/jMRAjCObLsDC93lmPpbFx//t72UOdfcSHyI88H9Dy1ZQU6VS47Y1OmmuFY2q+4cc+ABr7KLqyAEy0i7vny3QRD6GJ1KUwLbOEBs6i1176P7Jv3XBBPAG02bgGT9CfrjEM2r8Q2gDFwsv9Q1hXEOdsgpqnxZxlkDVc2CGhLb9s2G9hA1vP1Q465luis4lk4cApjbWsJxaPC7GUkElUXTUqeOg6Y/x3qfDoZo8t0458rrjDAKw==,iv:MvbleZdHVEXpNV/ttCfDuL82cjAO+TDQka0xd5SpAZM=,tag:K+dOCD+aQfIhRo282tw5jg==,type:str]
sops:
  age:
    - recipient: age1qlg79k9uz2a523qvklflq5xzrx7w9h8hjj8hhjg5spqr2he57acqret8fl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWkdFVkxrQTliYTNLMmh3
        RlJFSjNxNUNOZ2RCZUc5MCtlZzhSUy9hNFc4CkNxalZmUTJiZWtLWVZMZ3JZTE9o
        WGw5Y1F2Ynh4dUV3ZFNucEM1R2YzN2cKLS0tIGpRT2IwcVVDYXRzNjBrSWp1K0dS
        c2xwTTVxc2NjL0ozR2gvNWRuWTA5encKYDdHiNcehOZqqUXNbTkHqiVe61wScP12
        GPMSS9sMPi87PMBJpx/LqlmYYhVAUOIMUSSWy2HXbDA6w9c17Rua9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-14T12:24:49Z"
  mac: ENC[AES256_GCM,data:PDR0NRh0mrRKntrDP6jHWn7b18mI9/uVyD9pHfsVqaTk1ax4f2KQXDqBTsPACiCcOxjusLWmLuaZoVksQ0+ZSk/msTe/H6V8WwItikUH5HmlMAomuqeSraM1F5koz1UGI+xyXfZgOxQP6wiCxpDzfAljDxM7ogIcv0O9p71HsgE=,iv:Y4FN7c5N6ZVQ0wOkrXFa36kTCoUrnc8AUUzrA7lwZlk=,tag:e6ZFBlEmmeo8/cntyiy1BA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
